bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from bookstoreapp import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^bookstoreapp/', include('bookstoreapp.urls')),
    url(r'^admin/', admin.site.urls),
]

bookstoreapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'bookstoreapp'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='indexamos'),
    url(r'^createbook$', views.bookcreate, name='bookcreate'),
    url(r'^createeditor$', views.editorcreate, name='editorcreate'),
    url(r'^createauthor$', views.authorcreate, name='authorcreate'),
    url(r'^createcategory$', views.categorycreate, name='authorcreate'),
    url(r'^books_category_(?P<category_id>[0-9]+)/$', views.category_view, name='category_view'),
#    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
#    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

bookstoreapp/models.py
from django.db import models
from django.forms import ModelForm


class Editor(models.Model):
    name = models.CharField(max_length=256, default="")

    def __str__(self):
        return self.name


class EditorForm(ModelForm):
    class Meta:
        model = Editor
        fields = ['name']


class Author(models.Model):
    name = models.CharField(max_length=256, default="")

    def __str__(self):
        return self.name


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['name']


class Category(models.Model):
    name = models.CharField(max_length=256, default="")

    def __str__(self):
        return self.name


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name']


class Book(models.Model):
    name = models.CharField(max_length=256, default="")
    editor = models.ForeignKey(Editor)
    category = models.ForeignKey(Category)
    author = models.ForeignKey(Author)


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['category', 'name', 'author', 'editor']

bookstoreapp/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.http import HttpResponseRedirect
from bookstoreapp.models import *


def bookcreate(request):
    if request.method == "GET":
        form = BookForm()
        return render(request, 'bookstoreapp/create.html', {'form': form, 'object_type': 'Book'})
    elif request.method == "POST":
        form = BookForm(request.POST)
        form.save()
        return render(request, 'bookstoreapp/saved.html', {'object_type': 'Book', 'name': form.data['name']})


def editorcreate(request):
    if request.method == "GET":
        form = EditorForm()
        return render(request, 'bookstoreapp/create.html', {'form': form, 'object_type': 'Editor'})
    elif request.method == "POST":
        form = EditorForm(request.POST)
        form.save()
        return render(request, 'bookstoreapp/saved.html', {'object_type': 'Editor', 'name': form.data['name']})


def authorcreate(request):
    if request.method == "GET":
        form = AuthorForm()
        return render(request, 'bookstoreapp/create.html', {'form': form, 'object_type': 'Author'})
    elif request.method == "POST":
        form = AuthorForm(request.POST)
        form.save()
        return render(request, 'bookstoreapp/saved.html', {'object_type': 'Author', 'name': form.data['name']})


def categorycreate(request):
    if request.method == "GET":
        form = CategoryForm()
        return render(request, 'bookstoreapp/create.html', {'form': form, 'object_type': 'Category'})
    elif request.method == "POST":
        form = CategoryForm(request.POST)
        form.save()
        return render(request, 'bookstoreapp/saved.html', {'object_type': 'Category', 'name': form.data['name']})


class IndexView(generic.ListView):
    template_name = 'bookstoreapp/index.html'
    context_object_name = 'category_list'

    def get_queryset(self):
        return Category.objects.all()


def category_view(request, category_id):
    try:
        book_list = Book.objects.filter(category_id=category_id)
        category = Category.objects.get(id=category_id).name
        return render(request, 'bookstoreapp/booklist.html', {'book_list': book_list, 'category': category})
    except:
        return render(request, 'bookstoreapp/booklist.html', {'book_list': [], 'category': ''})

bookstoreapp/templates/actionlist.html
{% extends 'bookstoreapp/layout/layout.html' %}
{% block title %}Action list{% endblock %}
{% block content %}
<h2>{{ object_type }} with name: <br> '{{ name }}' <br>saved! </h2>
    <form action=".">
        <button type="submit" class="btn btn-success">Go back</button>
    </form>
{% endblock %}

bookstoreapp/templates/bookstoreapp/booklist.html
{% extends 'bookstoreapp/layout/layout.html' %}

{% block title %}Book List{% endblock %}
{% block content %}

  <div class="well well-sm">
  <h2>{{ category }}</h2>
  {% if book_list and  category %}

  <p class="text-center">Table 1: Books for {{ category }}</p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Book Name</th>
        <th>Author</th>
        <th>Editor</th>
      </tr>
    </thead>
    <tbody>
    {% for book in book_list %}
       <tr>
          <td>{{ book.name }}</td>
          <td>{{ book.author }}</td>
          <td>{{ book.editor }}</td>
       </tr>
    {% endfor %}
    </tbody>
  </table>
  </div>
  {% elif category %}
  <p>No books available for this category.</p>
  {% else %}
 <h3>Wrong category selection</h3>
{% endif %}

{% endblock %}

bookstoreapp/templates/bookstoreapp/create.html
{% extends 'bookstoreapp/layout/layout.html' %}

{% block title %}Create record{% endblock %}
{% block content %}
    <h2>Insert  {{ object_type }} </h2>
    <form method="POST" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}

bookstoreapp/templates/bookstoreapp/index.html
{% extends 'bookstoreapp/layout/layout.html' %}

{% block title %}Category list{% endblock %}
{% block content %}
<h2>Please choose a book category from the list</h2>


    {% if category_list %}
    <div class="well well-sm">
    <ul>
        {% for category in category_list %}
             <li><a href="{% url 'bookstoreapp:category_view' category_id=category.id %}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No categories available.</p>
    </div>
    {% endif %}

{% endblock %}

bookstoreapp/templates/bookstoreapp/layout/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
</head>
<body>

<div class="container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

bookstoreapp/templates/bookstoreapp/saved.html
{% extends 'bookstoreapp/layout/layout.html' %}
{% block title %}Saved info{% endblock %}
{% block content %}
<h2>{{ object_type }} with name: <br> '{{ name }}' <br>saved! </h2>
    <form action=".">
        <button type="submit" class="btn btn-success">Go back</button>
    </form>
{% endblock %}